# Generated by Django 4.0.4 on 2022-05-31 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('explanation', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=256)),
                ('content', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='blog.categorymodel')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
