# Generated by Django 4.0.4 on 2022-05-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorymodel'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
